apiVersion: apps/v1
kind: Deployment
metadata:
    name: pangolin
    labels:
        app: pangolin
spec:
    replicas: 3
    selector:
        matchLabels:
            app: pangolin
    template:
        metadata:
            labels:
                app: pangolin
        spec:
            containers:
                - name: pangolin-echoserver
                  image: k8s.gcr.io/echoserver:1.4
                  ports:
                    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
    name: pangolin
spec:
    selector:
        app: pangolin
    ports:
        - protocol: TCP
          port: 8080
